apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-lokeshwaranr

spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-web-lokeshwaranr
  template:
    metadata:
      labels:
        app: flask-web-lokeshwaranr

    spec:
      containers:
        - name: flaskwebsite
          image: jp.icr.io/flaskwebsite/website
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
